import { Repeater, PMRChannel, EmergencyFreq, FMStation, HardwareRange } from '../types';

function seedId(prefix: string, index: number) {
  return `seed-${prefix}-${String(index).padStart(3, '0')}`;
}

export const SEED_DATA = {
  repeaters: [
    { id: seedId('rep', 0), loc: 'R0 GANEKOGORTA', rx: '145.600', tx: '145.000', off: '-0.600', t: '123.0' },
    { id: seedId('rep', 1), loc: 'R1 SOLLUBE', rx: '145.625', tx: '145.025', off: '-0.600', t: 'NONE' },
    { id: seedId('rep', 2), loc: 'R2 LA GARBEA', rx: '145.650', tx: '145.050', off: '-0.600', t: '123.0' },
    { id: seedId('rep', 3), loc: 'R3 PAGASARRI', rx: '145.675', tx: '145.075', off: '-0.600', t: '82.5' },
    { id: seedId('rep', 4), loc: 'R4 VALLE DE MENA', rx: '145.700', tx: '145.100', off: '-0.600', t: '123.0' },
    { id: seedId('rep', 5), loc: 'R5 EIBAR', rx: '145.725', tx: '145.125', off: '-0.600', t: '77.0' },
    { id: seedId('rep', 6), loc: 'R6 MONTE OIZ', rx: '145.750', tx: '145.150', off: '-0.600', t: '82.5' },
    { id: seedId('rep', 7), loc: 'R7 KARRANTZA', rx: '145.775', tx: '145.175', off: '-0.600', t: '123.0' },
    { id: seedId('rep', 8), loc: 'U78 PAGASARRI', rx: '438.850', tx: '431.250', off: '-7.600', t: '123.0' },
    { id: seedId('rep', 9), loc: 'U82 GANEKOGORTA', rx: '438.950', tx: '431.350', off: '-7.600', t: '123.0' },
    { id: seedId('rep', 10), loc: 'U84 OIZ UHF', rx: '439.000', tx: '431.400', off: '-7.600', t: '82.5' },
    { id: seedId('rep', 11), loc: 'U86 SOLLUBE UHF', rx: '439.050', tx: '431.450', off: '-7.600', t: '123.0' },
    { id: seedId('rep', 12), loc: 'ED2ZAA DMR BILBAO', rx: '438.225', tx: '430.625', off: '-7.600', t: 'CC 1' },
    { id: seedId('rep', 13), loc: 'ED2ZAB DMR SOLLUBE', rx: '438.525', tx: '430.925', off: '-7.600', t: 'CC 1' }
  ] as Repeater[],
  pmr: Array.from({ length: 16 }, (_, i) => {
    const freqs = ['446.00625', '446.01875', '446.03125', '446.04375', '446.05625', '446.06875', '446.08125', '446.09375', '446.10625', '446.11875', '446.13125', '446.14375', '446.15625', '446.16875', '446.18125', '446.19375'];
    return { id: seedId('pmr', i), c: (i + 1).toString(), f: freqs[i], m: 'NFM', p: i === 7 ? 'MID' : 'LOW', u: i === 7 ? 'EMERGENCIA' : 'Uso Libre' };
  }) as PMRChannel[],
  emerg: [
    { id: seedId('emg', 0), s: 'Salvamento Marítimo', f: '156.800', m: 'FM', n: 'Canal 16 Náutico Internacional', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 1), s: 'REM (Montaña)', f: '146.175', m: 'FM', n: 'Red Emergencia Montaña - Auxilio', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 2), s: 'Prot. Civil Basauri', f: '152.325', m: 'FM', n: 'Coordinación Local Protección Civil', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 3), s: 'Cruz Roja Euskadi', f: '164.308', m: 'FM', n: 'Operativos Cruz Roja', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 4), s: 'Emergencias Bizkaia', f: '146.508', m: 'FM', n: 'QAP Local - Coordinación Emergencias', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 5), s: 'Bomberos Bizkaia', f: '169.5125', m: 'FM', n: 'Consorcio Bomberos - Operativa Principal', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 6), s: 'Bomberos Bizkaia', f: '169.7625', m: 'FM', n: 'Consorcio Bomberos - Coordinación', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 7), s: 'DYA Euskadi', f: '144.800', m: 'FM', n: 'Asistencia Sanitaria Voluntaria', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 8), s: 'DYA Euskadi', f: '146.200', m: 'FM', n: 'Emergencias DYA', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 9), s: 'Osakidetza Ambulancias', f: '164.0625', m: 'FM', n: 'Coordinación ambulancias', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 10), s: 'Osakidetza Soporte Avanzado', f: '164.2875', m: 'FM', n: 'Emergencias sanitarias', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 11), s: 'SAMUR País Vasco', f: '155.275', m: 'FM', n: 'Emergencia sanitaria móvil', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 12), s: 'Puerto de Bilbao', f: '156.600', m: 'FM', n: 'Canal 12 - Operaciones portuarias', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 13), s: 'Puerto de Bilbao', f: '156.700', m: 'FM', n: 'Canal 14 - Control tráfico portuario', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 14), s: 'Puerto de Bilbao', f: '156.450', m: 'FM', n: 'Canal 9 - Comunicaciones internas', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 15), s: 'Capitán Marítima Bilbao', f: '157.850', m: 'FM', n: 'Canal 27 - Coordinación marítima', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 16), s: 'Metro de Bilbao', f: '160.050', m: 'FM', n: 'Comunicaciones trenes/control', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 17), s: 'Metro de Bilbao', f: '161.300', m: 'FM', n: 'Seguridad y mantenimiento', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 18), s: 'EuskoTren', f: '161.625', m: 'FM', n: 'Operaciones ferroviarias', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 19), s: 'Bilbobus', f: '169.2125', m: 'FM', n: 'Coordinación flota transporte urbano', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 20), s: 'Protección Civil Bilbao', f: '152.225', m: 'FM', n: 'Coordinación municipal Bilbao', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 21), s: 'Protección Civil Barakaldo', f: '152.425', m: 'FM', n: 'Coordinación municipal Barakaldo', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 22), s: 'Protección Civil Portugalete', f: '152.525', m: 'FM', n: 'Coordinación municipal Portugalete', tx: 'RX ONLY', type: 'EMERG' },
    { id: seedId('emg', 23), s: 'LEBB Loiu APP', f: '120.700', m: 'AM', n: 'Aproximación', tx: 'RX ONLY', type: 'AIR' },
    { id: seedId('emg', 24), s: 'LEBB Loiu Torre', f: '118.500', m: 'AM', n: 'Torre Control', tx: 'RX ONLY', type: 'AIR' },
    { id: seedId('emg', 25), s: 'LEBB Loiu Tierra', f: '121.700', m: 'AM', n: 'Rodadura', tx: 'RX ONLY', type: 'AIR' }
  ] as EmergencyFreq[],
  fm: [
    { id: seedId('fm', 0), e: 'Radio Nervión', f: '88.0', z: 'Bilbao', s: 'MAX' },
    { id: seedId('fm', 1), e: 'Los 40 Classic', f: '88.5', z: 'Bilbao', s: 'ALTA' },
    { id: seedId('fm', 2), e: 'Los 40 Bilbao', f: '89.5', z: 'Bilbao', s: 'ALTA' },
    { id: seedId('fm', 3), e: 'Radio 3 RNE', f: '90.3', z: 'Bizkaia', s: 'ALTA' },
    { id: seedId('fm', 4), e: 'Radio Euskadi', f: '91.7', z: 'Bizkaia', s: 'MAX' },
    { id: seedId('fm', 5), e: 'Radio 7', f: '92.7', z: 'Barakaldo', s: 'ALTA' },
    { id: seedId('fm', 6), e: 'Rock FM', f: '93.6', z: 'Bilbao', s: 'ALTA' },
    { id: seedId('fm', 7), e: 'Kiss FM', f: '95.2', z: 'Bilbao', s: 'MEDIA' },
    { id: seedId('fm', 8), e: 'Cadena SER', f: '96.5', z: 'Bilbao', s: 'ALTA' },
    { id: seedId('fm', 9), e: 'Euskadi Gaztea', f: '97.2', z: 'Bizkaia', s: 'ALTA' },
    { id: seedId('fm', 10), e: 'RNE 1', f: '99.2', z: 'Bizkaia', s: 'ALTA' },
    { id: seedId('fm', 11), e: 'Cadena 100', f: '100.0', z: 'Bilbao', s: 'ALTA' },
    { id: seedId('fm', 12), e: 'Onda Cero', f: '101.5', z: 'Bilbao', s: 'ALTA' },
    { id: seedId('fm', 13), e: 'Bizkaia Irratia', f: '102.6', z: 'Durangaldea', s: 'MEDIA' },
    { id: seedId('fm', 14), e: 'COPE Bilbao', f: '103.8', z: 'Bilbao', s: 'ALTA' },
    { id: seedId('fm', 15), e: 'Melodia FM', f: '104.5', z: 'Bilbao', s: 'MEDIA' },
    { id: seedId('fm', 16), e: 'Radio Maria', f: '105.8', z: 'Bilbao', s: 'BAJA' },
    { id: seedId('fm', 17), e: 'Hit FM', f: '106.3', z: 'Bilbao', s: 'MEDIA' },
    { id: seedId('fm', 18), e: 'Euskadi Irratia', f: '107.4', z: 'Bizkaia', s: 'ALTA' },
    { id: seedId('fm', 19), e: 'Radio Gorbea', f: '93.1', z: 'Vitoria/Sur', s: 'BAJA' },
    { id: seedId('fm', 20), e: 'Onda Vasca', f: '90.1', z: 'Bilbao', s: 'ALTA' },
    { id: seedId('fm', 21), e: 'Europa FM', f: '98.4', z: 'Bilbao', s: 'ALTA' },
    { id: seedId('fm', 22), e: 'Radio Tropical', f: '102.9', z: 'Bilbao', s: 'MEDIA' },
    { id: seedId('fm', 23), e: 'Arratia Irratia', f: '104.9', z: 'Igorre', s: 'BAJA' },
    { id: seedId('fm', 24), e: 'Radio Vitoria', f: '104.1', z: 'Álava/Sur', s: 'BAJA' },
    { id: seedId('fm', 25), e: 'Radio Popular', f: '92.2', z: 'Bilbao', s: 'ALTA' },
    { id: seedId('fm', 26), e: 'Kosta Irratia', f: '104.7', z: 'Bakio', s: 'BAJA' },
    { id: seedId('fm', 27), e: 'Tas-Tas Irratia', f: '97.0', z: 'Bilbao', s: 'BAJA' },
    { id: seedId('fm', 28), e: 'Irola Irratia', f: '107.5', z: 'Irala', s: 'BAJA' },
    { id: seedId('fm', 29), e: '97 Irratia', f: '97.0', z: 'Bilbao', s: 'BAJA' },
    { id: seedId('fm', 30), e: 'Radio Encartaciones', f: '101.9', z: 'Zalla', s: 'BAJA' },
    { id: seedId('fm', 31), e: 'Bilbo Hiria', f: '96.0', z: 'Bilbao', s: 'BAJA' },
    { id: seedId('fm', 32), e: 'Loca FM', f: '105.4', z: 'Bilbao', s: 'MEDIA' },
    { id: seedId('fm', 33), e: 'Antena 3 RNE', f: '103.2', z: 'Bizkaia', s: 'ALTA' },
    { id: seedId('fm', 34), e: 'Radio Marca', f: '103.4', z: 'Bilbao', s: 'MEDIA' },
    { id: seedId('fm', 35), e: 'Radio 5 RNE', f: '100.7', z: 'Bizkaia', s: 'ALTA' },
    { id: seedId('fm', 36), e: 'Hala Bedi', f: '107.4', z: 'Vitoria', s: 'BAJA' },
    { id: seedId('fm', 37), e: 'Cadena Dial', f: '88.8', z: 'Bilbao', s: 'ALTA' },
    { id: seedId('fm', 38), e: 'Radio Oro', f: '95.2', z: 'Bilbao', s: 'MEDIA' },
    { id: seedId('fm', 39), e: 'Radio Candela', f: '98.0', z: 'Bilbao', s: 'BAJA' },
    { id: seedId('fm', 40), e: 'Very Bilbao', f: '100.9', z: 'Bilbao', s: 'MEDIA' },
    { id: seedId('fm', 41), e: 'Tropical FM', f: '102.2', z: 'Bilbao', s: 'BAJA' }
  ] as FMStation[],
  hardware: [
    { id: seedId('hw', 0), r: '65.0 - 108.0', s: 'FM Comercial', u: 'Radiodifusión FM (WFM)', m: 'WFM', tx: 'RX' },
    { id: seedId('hw', 1), r: '108.0 - 117.9', s: 'Banda Aérea', u: 'VOR / Navegación (Solo Balizas)', m: 'AM', tx: 'RX' },
    { id: seedId('hw', 2), r: '118.0 - 136.9', s: 'Banda Aérea', u: 'Comunicaciones Voz Aérea (AM)', m: 'AM', tx: 'RX' },
    { id: seedId('hw', 3), r: '144.0 - 144.150', s: '2M Amateur', u: 'CW (Telegrafía) - Uso Exclusivo', m: 'CW', tx: 'TX OK' },
    { id: seedId('hw', 4), r: '144.150 - 144.4', s: '2M Amateur', u: 'SSB (Banda Lateral) / DX', m: 'USB', tx: 'TX OK' },
    { id: seedId('hw', 5), r: '144.5 - 144.9', s: '2M Amateur', u: 'Todos los Modos / Digital / SSTV', m: 'FM', tx: 'TX OK' },
    { id: seedId('hw', 6), r: '145.0 - 145.175', s: '2M Amateur', u: 'Entrada Repetidores (R0-R7)', m: 'FM', tx: 'TX OK' },
    { id: seedId('hw', 7), r: '145.2 - 145.575', s: '2M Amateur', u: 'FM Simplex (145.500 Llamada)', m: 'FM', tx: 'TX OK' },
    { id: seedId('hw', 8), r: '145.6 - 145.775', s: '2M Amateur', u: 'Salida Repetidores (R0-R7)', m: 'FM', tx: 'TX OK' },
    { id: seedId('hw', 9), r: '145.8 - 146.0', s: '2M Amateur', u: 'Satélites (ISS Downlink)', m: 'FM', tx: 'TX OK' },
    { id: seedId('hw', 10), r: '146.0 - 174.0', s: 'VHF Pro', u: 'Servicios Profesionales / Caza / Emerg', m: 'FM', tx: 'TX OK' },
    { id: seedId('hw', 11), r: '430.0 - 432.0', s: '70cm Amateur', u: 'CW / SSB / Digital', m: 'USB', tx: 'TX OK' },
    { id: seedId('hw', 12), r: '433.0 - 433.575', s: '70cm Amateur', u: 'FM Simplex (433.500 Llamada)', m: 'FM', tx: 'TX OK' },
    { id: seedId('hw', 13), r: '438.650 - 439.425', s: '70cm Amateur', u: 'Salida Repetidores UHF', m: 'FM', tx: 'TX OK' },
    { id: seedId('hw', 14), r: '446.0 - 446.2', s: 'PMR446', u: 'Uso Libre sin licencia', m: 'NFM', tx: 'TX OK' }
  ] as HardwareRange[]
};
