import { QSO, ContestQSO } from '../types';

export function exportToJSON(data: any[], filename: string) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportToEDI(contestLogs: ContestQSO[], contestId: string, myCall: string, myLoc: string, band: string) {
  if (contestLogs.length === 0) return;
  const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');

  let h = `[REG1TEST;1]\nTName=${contestId}\nTDate=${dateStr};${dateStr}\nPCall=${myCall}\nPWWLo=${myLoc}\nPSect=SINGLE-PORTABLE\nPBand=${band}\n[Remarks]\nGenerated by QRZLog Terminal\n[QSORecords;${contestLogs.length}]\n`;
  let r = contestLogs.map(q => `${q.date};${q.time};${q.callsign};1;${q.s_rst};${q.s_nr};${q.r_rst};${q.r_nr};${q.r_loc};`).join('\n');

  const blob = new Blob([h + r], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${contestId}_${dateStr}_${band.replace(' ', '')}.edi`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportToCSV(repeaters: any[], pmr: any[], emerg: any[]) {
  const headers = [
    "Location", "Name", "Frequency", "Duplex", "Offset", "Tone",
    "rToneFreq", "cToneFreq", "DtcsCode", "DtcsPolarity",
    "RxDtcsCode", "CrossMode", "Mode", "TStep", "Skip",
    "Power", "Comment", "URCALL", "RPT1CALL", "RPT2CALL", "DVCODE"
  ].join(",");

  let loc = 1;
  const rows: string[] = [];
  const fmt = (f: string) => parseFloat(f).toFixed(5);
  const name = (s: string) => s.replace(/,/g, '').substring(0, 8).toUpperCase();
  const magicCols = "023,NN,023,Tone->Tone";

  repeaters.forEach(r => {
    let duplex = '';
    let offset = '0.00000';
    if (r.off && r.off !== '0.000') {
      const o = parseFloat(r.off);
      duplex = o < 0 ? '-' : '+';
      offset = fmt(Math.abs(o).toString());
    }

    let toneStr = '';
    let cTone = '88.5';
    if (r.t && r.t !== 'NONE' && !r.t.startsWith('CC')) {
      toneStr = 'Tone';
      cTone = parseFloat(r.t).toFixed(1);
    }

    rows.push([
      loc++, name(r.loc), fmt(r.rx), duplex, offset, toneStr, "88.5", cTone, magicCols, "FM", "12.5", "", "10.0W", "", "", "", "", ""
    ].join(','));
  });

  const csv = [headers, ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'MASTER_H8.csv';
  a.click();
  URL.revokeObjectURL(url);
}
